spring.application.name=realestate-backend

# Supabase PostgreSQL Database
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=postgres.vcqwagbwazbknqjqbtus

spring.datasource.password=0210@Gopikesav

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File upload
spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/images/**

# IMPORTANT FOR RENDER
server.port=${PORT:8080}