spring.application.name=realestate-backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://dpg-d83gqf9kh4rs73ajipd0-a.oregon-postgres.render.com:5432/realestate_idy6
spring.datasource.username=admin
spring.datasource.password=JXbtzvgX7d8CEEPe3OHicIq5ak1m0w9K

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File upload
spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/images/**

# IMPORTANT FOR RENDER
server.port=${PORT:8080}