spring.application.name=realestate-backend

# ✅ PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/realestate_db
spring.datasource.username=postgres
spring.datasource.password=1234

# ✅ JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ✅ File upload (images)
spring.web.resources.static-locations=file:uploads/
spring.mvc.static-path-pattern=/images/**

# ✅ Server
server.port=8080